export const transformationItems = [
    {
      id: 1,
      name: "Mailén",
      beforeImage: "/cambios/MAILEN-ANTES.jpg",
      afterImage: "/cambios/MAILEN-DESPUES.jpg",
      weeks: 10,
    },
    {
      id: 2,
      name: "Andrea",
      beforeImage: "/cambios/ANDREA-ANTES.jpg",
      afterImage: "/cambios/ANDREA-DESPUES.jpg",
      weeks: 6},
    {
      id: 3,
      name: "Vicky",
      beforeImage: "/cambios/VICKY-ANTES.jpg",
      afterImage: "/cambios/VICKY-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 4,
      name: "Eliana",
      beforeImage: "/cambios/ELIANA-ANTES.jpg",
      afterImage: "/cambios/ELIANA-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 5,
      name: "Manuel",
      beforeImage: "/cambios/MANUEL-ANTES.jpg",
      afterImage: "/cambios/MANUEL-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 6,
      name: "Mely",
      beforeImage: "/cambios/MELY-ANTES.jpg",
      afterImage: "/cambios/MELY-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 7,
      name: "Gustavo",
      beforeImage: "/cambios/GUSTAVO-ANTES.jpg",
      afterImage: "/cambios/GUSTAVO-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 8,
      name: "Juani",
      beforeImage: "/cambios/JUANI-ANTES.jpg",
      afterImage: "/cambios/JUANI-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 9,
      name: "Pablo",
      beforeImage: "/cambios/PABLO-ANTES.jpg",
      afterImage: "/cambios/PABLO-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 10,
      name: "Matias",
      beforeImage: "/cambios/MATIAS-ANTES.jpg",
      afterImage: "/cambios/MATIAS-DESPUES.jpg",
      weeks: 16,
    },
    {
      id: 11,
      name: "Milagros",
      beforeImage: "/cambios/MILAGROS-ANTES.jpg",
      afterImage: "/cambios/MILAGROS-DESPUES.jpg",
      weeks: 16,
    },
  ]